version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "ruby"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "standardrb"