# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: XXX

staging:
  forest_admin:
    env_secret: XXX
    auth_secret: XXX
  contentful:
    space_id: XXX
    delivery_access_token: XXX

production:
  forest_admin:
    env_secret: XXX
    auth_secret: XXX
  contentful:
    space_id: XXX
    delivery_access_token: XXX