# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: XXX

default: &default
  google:
    client_id: XXX
    client_secret: XXX

  contentful:
    space_id: XXX
    webhook_password: CreateYourOwnStrongPassword!
    delivery_access_token: XXX
    preview_access_token: XXX

test:
  <<: *default

development:
  <<: *default

  forest_admin:
    env_secret: XXX
    auth_secret: XXX

staging:
  <<: *default

  postmark_api_token: XXX

  aws:
    access_key_id: XXX
    secret_access_key: XXX
    region: eu-west-2
    bucket: rapid_rails_staging

  forest_admin:
    env_secret: XXX
    auth_secret: XXX

production:
  <<: *default

  postmark_api_token: XXX

  aws:
    access_key_id: XXX
    secret_access_key: XXX
    region: eu-west-2
    bucket: rapid_rails_production

  forest_admin:
    env_secret: XXX
    auth_secret: XXX
