# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: XXX

active_record_encryption:
  primary_key: XXX
  deterministic_key: XXX
  key_derivation_salt: XXX

default: &default
  google:
    client_id: XXX
    client_secret: XXX

  contentful:
    space_id: XXX
    webhook_secret_token: CreateYourOwnStrongPassword!
    delivery_access_token: XXX
    preview_access_token: XXX

test:
  <<: *default

development:
  <<: *default

staging:
  <<: *default

  postmark_api_token: XXX

  cloudflare:
    account_id: XXX
    access_key_id: XXX
    secret_access_key: XXX
    bucket: rapidrails
    sitemaps_bucket: rapidrails-sitemaps
    sitemaps_public_bucket_url: https://xxx.r2.dev

production:
  <<: *default

  postmark_api_token: XXX

  cloudflare:
    account_id: XXX
    access_key_id: XXX
    secret_access_key: XXX
    bucket: rapidrails
    sitemaps_bucket: rapidrails-sitemaps
    sitemaps_public_bucket_url: https://xxx.r2.dev
