# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: XXX

contentful:
  space_id: XXX
  delivery_access_token: XXX

development:
  google:
    client_id: XXX
    client_secret: XXX

staging:
  forest_admin:
    env_secret: XXX
    auth_secret: XXX
  contentful:
    space_id: XXX
    delivery_access_token: XXX

  postmark_api_token: XXX

  aws:
    access_key_id: XXX
    secret_access_key: XXX
    region: eu-west-2
    bucket: rapid_rails_staging

  google:
    client_id: XXX
    client_secret: XXX

production:
  forest_admin:
    env_secret: XXX
    auth_secret: XXX

  postmark_api_token: XXX

  aws:
    access_key_id: XXX
    secret_access_key: XXX
    region: eu-west-2
    bucket: rapid_rails_production

  google:
    client_id: XXX
    client_secret: XXX
