---
:verbose: false
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>
:max_retries: <%= ENV['SIDEKIQ_MAX_RETRY'] || 5 %>

# timeout to 8 for Heroku, longer if you manage your own systems.
:timeout: 8

:queues:
  # Weighted job priorities: the weight you put on each queue will
  # determine how frequently it'll be scanned relatively compared to other queues.
  - [critical, 100]
  - [default, 50]
  - [mailers, 25]
  - [low, 1]
